services:
  postgres_db:
    image: postgres:14-alpine
    container_name: postgres_db
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - tododb:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=tododb
    networks:
      - app_network

  
  todoapp:
    image: todoapp
    build:
      context: .
    ports:
      - "5009:80"
    restart: always
    depends_on:
      - postgres_db
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres_db:5432;Database=tododb;Username=postgres;Password=postgres;
      - ASPNETCORE_URLS=http://+:80
    networks:
      - app_network

networks:
  app_network:
    driver: bridge 

volumes:
  tododb:
